package:
  name: pykdl
  version: 1.3.0.pyrapid

source:
    git_url: https://github.com/jf---/orocos_kinematics_dynamics.git
    git_tag: master

build:
  number: 1
  binary_relocation: true # (defaults to true)

requirements:
  build:
    - cmake
    - python
    - sip
    - eigen # https://binstar.org/meznom/eigen/

  run:
    - sip
    - python

test:
  requires:
    - sip
    - python
  imports:
    - PyKDL

# test:
#   commands:
#     - wget --help

about:
  home: http://www.orocos.org
  license: GPL 2.1
